"""Phase 1C: add users table

Revision ID: 14ff63e46002
Revises: 8c02ad9ab4cf
Create Date: 2025-11-03 17:50:04.259875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ff63e46002'
down_revision: Union[str, None] = '8c02ad9ab4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
