"""Phase 1B: create users table

Revision ID: 8c02ad9ab4cf
Revises: 412b50730cfb
Create Date: 2025-11-03 17:47:03.685793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c02ad9ab4cf'
down_revision: Union[str, None] = '412b50730cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
