"""Phase_02: unified schema build

Revision ID: 96070f73415d
Revises: 8f4dd0c3ae03
Create Date: 2025-11-03 20:28:08.025175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96070f73415d'
down_revision: Union[str, None] = '8f4dd0c3ae03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
